export default {
  bannerUrl: '',
  typesUrl: '/api/v1/types',
  commoditiesUrl: '/api/v1/commodities/pages',
  commodityUrl: '/api/v1/commodity',
  infoUrl: '/api/v1/commodity/info/',
  auctionUrl: '/api/v1/auction/getCurrentAuction',
  myAuctionUrl: '/api/v1/auction/g',
  allAddressUrl: '/api/v1/receivingInfo/all',
  myMsgUrl: '/api/auth/user/myMsg',
  sendBindPhoneUrl: '/api/v1/sms/bind',
  wechatLoginUrl: '/api/v1/oauth/wechaturl',
  wechatLogin: '/api/auth/login/wechatLogin',
  bindPhone: '/api/auth/user/bindPhone',
  addPriceUrl: '/api/v1/bidders/addPrice',
  addAddressUrl: '/api/v1/receivingInfo/add',
  delAddressUrl: '/api/v1/receivingInfo/del',
  updateAddressUrl: '/api/v1/receivingInfo/update',
  setDefaultAddressUrl: '/api/v1/receivingInfo/setDefault',
  followListUrl: '/api/v1/bidders/getFollowList'
}